# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZendeskiOS' do
  pod 'ZendeskAnswerBotSDK' 
  pod 'ZendeskChatSDK'      
  pod 'ZendeskSupportSDK'   
end
